# Generated by Django 4.2.2 on 2023-10-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email_academico', models.EmailField(max_length=254, unique=True)),
                ('rol_usuario', models.CharField(blank=True, max_length=20)),
                ('area_academica_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
